### ISSUE TITLE
키파일 설정 서버로 분리 

### ISSUE THREAD

**Issue by JunHoPark93** [Nexters/doctor24-server#19]
배포 작업 이전에 공공 데이터 이용 발급 key를 private repository에서 로드 하게 끔 변경
spring cloud config를 사용 예정

**Comment by aj1155** [comment]
요즘 config서버를 로컬에 같이 띄우기도 하더라 근데 우리는 장비 스펙이 워낙 구리니 그냥 다른 곳에 두자
